package com.soaint.informacioncliente;

import java.util.Iterator;
import java.util.List;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c Development Build 12.2.1.0.0.1157
public class InformacionClienteClient {
    public static void main(String[] args) {
        ServicioInformacionCliente servicioInformacionCliente = new ServicioInformacionCliente();
        InformacionClientePort informacionClientePort = servicioInformacionCliente.getInformacionCliente();
        // Add your code to call the desired methods.

        ClienteType rq = new ClienteType();
        rq.setEdad(23);

        ListaCLienteType rs = informacionClientePort.consultarClientes(rq);

        List<ClienteType> listaCliente = rs.getListadoClientes();

        Iterator listaClienteIte = listaCliente.iterator();

        while (listaClienteIte.hasNext()) {
    
            ClienteType currentCli = (ClienteType) listaClienteIte.next();
            
            System.out.println(currentCli.getNombres());

        }


    }
}
