
package com.soaint.informacioncliente;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "ServicioInformacionCliente", targetNamespace = "http://www.soaint.com/InformacionCliente/",
                  wsdlLocation =
                  "http://localhost:8088/consultarClientes?WSDL#%7Bhttp%3A%2F%2Fwww.soaint.com%2FInformacionCliente%2F%7DServicioInformacionCliente")
public class ServicioInformacionCliente extends Service {

    private final static URL SERVICIOINFORMACIONCLIENTE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOINFORMACIONCLIENTE_EXCEPTION;
    private final static QName SERVICIOINFORMACIONCLIENTE_QNAME =
        new QName("http://www.soaint.com/InformacionCliente/", "ServicioInformacionCliente");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:8088/consultarClientes?WSDL#%7Bhttp%3A%2F%2Fwww.soaint.com%2FInformacionCliente%2F%7DServicioInformacionCliente");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOINFORMACIONCLIENTE_WSDL_LOCATION = url;
        SERVICIOINFORMACIONCLIENTE_EXCEPTION = e;
    }

    public ServicioInformacionCliente() {
        super(__getWsdlLocation(), SERVICIOINFORMACIONCLIENTE_QNAME);
    }

    public ServicioInformacionCliente(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOINFORMACIONCLIENTE_QNAME, features);
    }

    public ServicioInformacionCliente(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOINFORMACIONCLIENTE_QNAME);
    }

    public ServicioInformacionCliente(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOINFORMACIONCLIENTE_QNAME, features);
    }

    public ServicioInformacionCliente(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioInformacionCliente(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InformacionClientePort
     */
    @WebEndpoint(name = "InformacionCliente")
    public InformacionClientePort getInformacionCliente() {
        return super.getPort(new QName("http://www.soaint.com/InformacionCliente/", "InformacionCliente"),
                             InformacionClientePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InformacionClientePort
     */
    @WebEndpoint(name = "InformacionCliente")
    public InformacionClientePort getInformacionCliente(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.soaint.com/InformacionCliente/", "InformacionCliente"),
                             InformacionClientePort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOINFORMACIONCLIENTE_EXCEPTION != null) {
            throw SERVICIOINFORMACIONCLIENTE_EXCEPTION;
        }
        return SERVICIOINFORMACIONCLIENTE_WSDL_LOCATION;
    }

}
